Support for loading range-compressed data
IMS-AS-LUH/sar-sim pull request #4
Opened 2022-06-29 15:29 UTC by nrother

We have a lot of pre-existing data, often already range-compressed. This PR adds code to support loading such captures and process them.

I also added a somewhat formal spec of the format the simulator can load, called "sardata".

2022-07-18 19:43 UTC, cbcf requested changes

2022-07-18 19:43 UTC, cbcf commented on sarsim/sardata.py
> +        sim.image_count_y = cfg['params'].getint('gbp_image_pixels_ range', fallback=1024)
Is this correct?

2022-07-18 19:43 UTC, cbcf commented on sarsim/sardata.py
> +        sim.azimuth_compression_beam_limit = cfg['params'].getfloat('gbp_beam_limit', fallback=30)
Exra Whitespace

2022-07-18 19:43 UTC, cbcf commented on sarsim/sardata.py
> +        sim.image_count_y = cfg['params'].getint('gbp_image_pixels_ range', fallback=1024)
xy swap? also "pixels_ range"

2022-07-19 08:21 UTC, nrother commented on sarsim/sardata.py
> +        sim.azimuth_compression_beam_limit = cfg['params'].getfloat('gbp_beam_limit', fallback=30)
Fixed

2022-07-19 08:21 UTC, nrother commented on sarsim/sardata.py
> +        sim.image_count_y = cfg['params'].getint('gbp_image_pixels_ range', fallback=1024)
Space is fixed, X/Y should be correct (Y is Range)

2022-07-19 10:48 UTC, cbcf approved these changes

2022-07-19 10:48 UTC, merged